# Generated by Django 4.1.13 on 2025-11-05 00:34

import BackendApp.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Academics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("college_name", models.CharField(max_length=255)),
                ("graduation_date", models.CharField(max_length=50)),
                ("course", models.CharField(max_length=255)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Academic",
                "verbose_name_plural": "Academics",
                "db_table": "academics",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Achievements",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("achievement_point", models.TextField()),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "db_table": "achievements",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="ApplicantBasicInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid email address.",
                                regex="^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$",
                            )
                        ],
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid LinkedIn URL.",
                                regex="^https?://(www\\.)?linkedin\\.com/",
                            )
                        ],
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid GitHub URL.",
                                regex="^https?://(www\\.)?github\\.com/",
                            )
                        ],
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Applicant Basic Information",
                "verbose_name_plural": "Applicant Basic Information",
                "db_table": "applicant_basic_info",
            },
        ),
        migrations.CreateModel(
            name="Applications",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_name", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                (
                    "job_link",
                    models.URLField(
                        max_length=500,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                ("resume_file_path", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Applied", "Applied"),
                            ("Rejected", "Rejected"),
                            ("Timed out", "Timed out"),
                            ("Processed", "Processed"),
                            ("Accepted", "Accepted"),
                            ("Interview", "Interview"),
                        ],
                        default="Applied",
                        max_length=50,
                        validators=[BackendApp.models.validate_status],
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "db_table": "applications",
            },
        ),
        migrations.CreateModel(
            name="Experiences",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("experience_name", models.CharField(max_length=255)),
                ("start_date", models.CharField(max_length=50)),
                ("end_date", models.CharField(max_length=50)),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                ("experience_explanation", models.TextField()),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experiences",
                "db_table": "experiences",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("project_info", models.TextField()),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "db_table": "projects",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectSkills",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Project Skill",
                "verbose_name_plural": "Project Skills",
                "db_table": "project_skills",
            },
        ),
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("skill_name", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "db_table": "skills",
            },
        ),
        migrations.CreateModel(
            name="UserSkills",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "skill",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_skill",
                        to="BackendApp.skills",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Skill",
                "verbose_name_plural": "User Skills",
                "db_table": "user_skills",
            },
        ),
        migrations.AddIndex(
            model_name="skills",
            index=models.Index(fields=["skill_name"], name="idx_skills_name"),
        ),
        migrations.AddIndex(
            model_name="skills",
            index=models.Index(fields=["category"], name="idx_skills_category"),
        ),
        migrations.AddField(
            model_name="projectskills",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_skills",
                to="BackendApp.projects",
            ),
        ),
        migrations.AddField(
            model_name="projectskills",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_skills",
                to="BackendApp.skills",
            ),
        ),
        migrations.AddIndex(
            model_name="projects",
            index=models.Index(
                fields=["display_order"], name="idx_projects_display_order"
            ),
        ),
        migrations.AddIndex(
            model_name="experiences",
            index=models.Index(
                fields=["display_order"], name="idx_experiences_display_order"
            ),
        ),
        migrations.AddIndex(
            model_name="applications",
            index=models.Index(fields=["status"], name="idx_applications_status"),
        ),
        migrations.AddIndex(
            model_name="applications",
            index=models.Index(
                fields=["company_name"], name="idx_applications_company_name"
            ),
        ),
        migrations.AddIndex(
            model_name="applicantbasicinfo",
            index=models.Index(fields=["email"], name="idx_applicant_basic_info_email"),
        ),
        migrations.AddIndex(
            model_name="achievements",
            index=models.Index(
                fields=["display_order"], name="idx_achievements_display_order"
            ),
        ),
        migrations.AddIndex(
            model_name="academics",
            index=models.Index(
                fields=["display_order"], name="idx_academics_display_order"
            ),
        ),
        migrations.AddIndex(
            model_name="userskills",
            index=models.Index(fields=["skill"], name="idx_user_skills_skill_id"),
        ),
        migrations.AddIndex(
            model_name="projectskills",
            index=models.Index(
                fields=["project"], name="idx_project_skills_project_id"
            ),
        ),
        migrations.AddIndex(
            model_name="projectskills",
            index=models.Index(fields=["skill"], name="idx_project_skills_skill_id"),
        ),
        migrations.AlterUniqueTogether(
            name="projectskills",
            unique_together={("project", "skill")},
        ),
    ]
