# Generated by Django 4.1.13 on 2025-11-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BackendApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiences",
            name="location",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
